server:
  port: 8001

security:
  basic:
    enabled: false
    user: admin
    password: admin00
  apikey:
    enabled: false
    token: 9a0697eb595309177ff10336f2801b5861833ac36315b7bbda3fd2e1619797d9

encrypt:
  key: secretkey
  # key_store:
  #   location: server.jks
  #   password: letmein
  #   alias: mytestkey
  #   secret: changeme

logging:
  level:
    root: WARN

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: ./configs
