server:
  host:
  port: 3001

security:
  basic:
    enabled: false
    user: admin
    password: admin00
  apikey:
    enabled: false
    token: 9a0697eb595309177ff10336f2801b5861833ac36315b7bbda3fd2e1619797d9

encrypt:
  key: secretkey

logging:
  level:
    root: WARN

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: ./configs
  nats:
    servers: nats://localhost:4222
    subject: springCloudBus
    auth:
      type: token
      token: S3cretT0ken
