server:
  host:
  port: 3001

security:
  apikey:
    enabled: true
    keylookup: "all:apikey"
    token: 9a0697eb5

encrypt:
  key: secretkey

logging:
  level:
    root: WARN

spring:
  profiles:
    active: native, git, vault
  cloud:
    config:
      server:
        native:
          searchLocations: ./configs
        git:
          uri: https://github.com/helderfarias/go-config-server-examples
          clone_dir: ./tmp
          force_pull: true
        vault:
          uri: http://localhost:8200
  nats:
    servers: nats://localhost:4222
    subject: springCloudBus
    auth:
      type: token
      token: S3cretT0ken
