server:
  host:
  port: 3001

security:
  basic:
    enabled: false
    user: admin
    password: admin00
  apikey:
    enabled: false
    keylookup: "header:apikey"
    token: 9a0697eb595309177ff10336f2801b5861833ac36315b7bbda3fd2e1619797d9

encrypt:
  key: secretkey

logging:
  level:
    root: WARN

spring:
  profiles:
    active: native, git, vault
  cloud:
    config:
      server:
        native:
          searchLocations: ./configs
        git:
          uri: https://github.com/helderfarias/go-config-server-examples
          clone_dir: ./tmp
          force_pull: true
        vault:
          uri: http://localhost:8200
  nats:
    servers: nats://localhost:4222
    subject: springCloudBus
    auth:
      type: token
      token: S3cretT0ken
